### ISSUE TITLE
Submit form from outside

### ISSUE THREAD

**Issue by romanlex** [erikras/react-final-form#13]
Hello. How I can submit form from outside sibling component? Example I want submit form by button from modal window

**Comment by romanlex** [comment]
Now I use Portal https://gist.github.com/romanlex/bf61fb0c3db2ef1a6c68cb07a0904da2 but I think need remote submit method (

**Comment by erikras** [comment]
Wow, look at you using `<Fragment>` already! 😮

Can you not pass `handleSubmit` to your portal component?

**Comment by romanlex** [comment]
if I remove handleSubmit my button doesnt work because buttons render to another domNode with Ract.createPortal

**Comment by erikras** [comment]
It's not very React-y, but I wonder if you could use the DOM itself to achieve this, by calling [`submit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit)?
```jsx
<form id="myForm" onSubmit={handleSubmit}> ... </form>
...
<button type="button" onClick={() => document.getElementById('myForm').submit()}>
  Submit
</button>
```

**Comment by codepunkt** [comment]
@romanlex it seems we ran into similar problems.

For me, calling `.submit()` on the form did not work & reloaded the whole app.
See [this tweet](https://twitter.com/code_punkt/status/937704024073297920) for more information on how i solved it.

Maybe you can even chime in and tell me why the heck the things i did actually worked, when `.submit()` doesn't.

**Comment by elrumordelaluz** [comment]
Beyond this little issue, the _switch_ from `redux-form` into `react-final-form` seems really simple.
Thanks @erikras for the great work!

Thanks @romanlex for the _workaround_, I am also pretty curious on why only this way works as expected.

**Comment by erikras** [comment]
[Made a FAQ about this](https://github.com/final-form/react-final-form/blob/master/docs/faq.md#how-can-i-trigger-a-submit-from-outside-my-form).

**Comment by romanlex** [comment]
Hello! Why I use Portal but not use ```document.getElementById()``` or submit by **Closure**?
Because I want use native state by react-final-form without any HOC with custom form state
I want disable button or another function. 
```
<button
              className="btn btn-outline-secondary btn-block"
              type="button"
              onClick={reset}
              disabled={submitting || pristine}
            >
              Reset form
            </button>
            <button
              className="btn btn-primary btn-block"
              type="submit"
              onClick={handleSubmit}
              disabled={submitting}
            >
              Submit
            </button>
```
