### ISSUE TITLE
Form can still be submitted even with validation errors

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/react-final-form#17]
Hey, https://github.com/erikras/react-final-form/issues/3 is still an issue.

I've updated the [codesandbox demo](https://codesandbox.io/s/23ynxmq4jy) to 1.1.0 and I can get all `errors` from the form, but I can still submit it.

Validation errors check should probably be added in `hasSyncErrors` [here](https://github.com/erikras/final-form/blob/master/src/FinalForm.js#L560), but how's [this test](https://github.com/erikras/final-form/blob/master/src/FinalForm.submission.test.js#L45) passing then.

Am I missing something? 🤔

**Comment by erikras** [comment]
Great reporting. Yep, that's a bug.

**Comment by erikras** [comment]
That test was broken, as there was an invalid registered field. 🤦‍♂️

**Comment by erikras** [comment]
Published fix in [`final-form v1.2.1`](https://github.com/final-form/final-form/releases/tag/v1.2.1).

**Comment by VladShcherbin** [comment]
@erikras yep, it's working now. Thank you! 🤗

**Comment by alex-shatalov** [comment]
Does final-form has analog of 'persistentSubmitErrors' like it was in redux-form ?
