### ISSUE TITLE
Change values

### ISSUE THREAD

**Issue by linashredinger** [erikras/react-final-form#18]
Hello! Is there any possibility to pass initial values after form created. Or change particular value from upper component. 
I prefill my form using query after form is rendered and I can not pass loaded values to inputs.
Thanks

**Comment by erikras** [comment]
Fix published in [`v1.1.1`](https://github.com/final-form/react-final-form/releases/tag/v1.1.1) check out [this new example](https://codesandbox.io/s/91w9ro3x9o).

**Comment by jasan-s** [comment]
@erikras for some reason the initial values dont change when using the Wizard Form. see example fork https://codesandbox.io/s/62vozkryxz
