### ISSUE TITLE
Feature Request: Support for Arrays of Objects

### ISSUE THREAD

**Issue by aherriot** [erikras/react-final-form#2]
One of the things that I love about `redux-form` compared to `formik` is that `redux-form` supports complex form data such as arrays of objects. Are there any plans to include similar functionality here?

**Comment by erikras** [comment]
> Are there any plans to include similar functionality here?

Yes.

**Comment by erikras** [comment]
To be clear, RFF already supports structures like `addresses[1].phones[2].areaCode`. What I am assuming you are referring to is the `push`, `pop`, etc. operations on arrays in your form. That is still to be developed...

**Comment by aherriot** [comment]
Good to know. Yes, the utilities that FieldArray provides is something I use all the time and love it.

**Comment by erikras** [comment]
Good news, folks. We have...

# [🎉 Field Arrays 🎉](https://medium.com/@erikras/final-form-arrays-and-mutators-13159cb7d285)

**Comment by davidhenley** [comment]
Has anyone figured out how to validate Field Arrays yet? I can't find an example and can't figure out what the docs for validate mean
