### ISSUE TITLE
Reset form after form submission succeed 

### ISSUE THREAD

**Issue by kalutheo** [erikras/react-final-form#21]
Hi there ! 
I was wondering how i can reset my form on successful submit ? 
Seems that we don't have access to the `reset()` function in `onSubmit()`. 
How can i handle that ? 
Thanks for the work by the way , react-final-form is awesome  :)

**Comment by scorchiowned** [comment]
Not sure if the best way to proceed with this but you can set a ref on the form instance and on your onSubmit callback fn access the forms reset prop as such

	onSubmit = values => {
		this.refs["user-form"].form.reset()
	};

**Comment by erikras** [comment]
Once the fix in #32 is released, the answer is:

```jsx
<Form
  onSubmit={onSubmit}
  initialValues={{ employed: true }}
  render={({ handleSubmit, reset }) => (
    <form
      onSubmit={event => {
        handleSubmit(event).then(() => {
          reset() // or could be passed directly to then()
        })
      }}
    >
    ...
    </form>
  }/>

```

**Comment by erikras** [comment]
Fix published in [`v1.1.1`](https://github.com/final-form/react-final-form/releases/tag/v1.1.1).

**Comment by davidhenley** [comment]
This is still not working for me on latest version.

```
<Form
      onSubmit={values => {
        return new Promise((res, rej) => {
          axios.post('/api/forms/creditdebit', values)
            .then(response => res())
            .catch(error => res({ error }));
        })
      }}
      component={CreditDebitForm}
    />
```

```
<Form onSubmit={e => {
      handleSubmit(e)
        .then(() => reset());
    }}>
```

**Comment by kalutheo** [comment]
Hi @erikras thanks for the fix i will try on my side and upgrade to v1.1.1

**Comment by kalutheo** [comment]
Hi @davidhenley i managed to make it work see this example : 

https://stackblitz.com/edit/react-final-form-reset-submit?file=index.js

**Comment by davidhenley** [comment]
Try it using component. It still doesn't work for me.

**Comment by davidhenley** [comment]
Does not work with your exact code using component.

Cannot read property 'then' of undefined

```
const { handleSubmit, reset, values, pristine, invalid, submitting, submitFailed, submitSucceeded } = props;

  return (
    <form onSubmit={event => {
      const promise = handleSubmit(event);
      console.log('heyyy :-D', promise);
      promise.then(() => {
        reset();
      })
      return promise;
    }}>
```

```
<Form
      onSubmit={(values) => {
        return new Promise(resolve => {
          const options = {
            to: [],
            subject: `${values.customer.description} ${values.type} Request ${format(new Date(), 'MMM D, YYYY h:mm a')}`,
            html: template(values, user)
          };

          axios.post('/api/forms/creditdebit', { values, options })
            .then(response => resolve())
            .catch(error => resolve({ error }));
        });
      }}
      component={CreditDebitForm}
    />
```

**Comment by davidhenley** [comment]
Changed this and it worked. This is super weird.

**Doesnt work**
```
<Form
      onSubmit={(values) => {
          return new Promise(resolve => 
            setTimeout(resolve, 3000);
          )
      }}
      component={CreditDebitForm}
    />
```

**Does work**
```
const onSubmit = (values) => {
      return new Promise(resolve => 
        setTimeout(resolve, 3000);
      )
  }
<Form
      onSubmit={onSubmit}
      component={CreditDebitForm}
    />
```

**Comment by erikras** [comment]
Here's a working sandbox with [my suggestion from above](https://github.com/final-form/react-final-form/issues/21#issuecomment-349024729).

[![Edit 🏁 React Final Form - Reset After Submit](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m40yyj2nyx)

**Comment by davidhenley** [comment]
Heads up, you cannot use .then on handleSubmit unless you disable your submit on invalid. The middleman does not return a promise so there is no .then

**Comment by stunaz** [comment]
@erikras wouldn't be best to pass the `reset` or maybe others helpers to `onSubmit`.

the signature would be like :
`onSubmit: (values: Object, callback: ?(errors: ?Object) => void, reset: Function, ....) => ?Object | Promise<?`

**Comment by klis87** [comment]
@stunaz  I completely agree. Especially we already have `callback`, which de facto is just setSubmitError action, so why not to add other actions, like `reset`.

@erikras  the problem with your promise solution is, that this is not always possible. For instance, when you use redux-saga instead of redux-thunk, you wont have promise at your disposal, so it is necessary to have a `reset` in `onSubmit` itself, so it could be passed to saga there for a later execution.

**Comment by stunaz** [comment]
opened an issue #69 to get more visibility

**Comment by ronn** [comment]
"Uncaught TypeError: Cannot read property 'then' of undefined at onSubmit"
:/

**Comment by shanebeehler** [comment]
Make sure you add return in front of fetch/axios or whatever library you're using to make POST request.

`    return fetch('/', {
      method: 'POST'......`

**Comment by ronn** [comment]
Solved putting form.reset() in the parent component

**Comment by NYCJacob** [comment]
any examples showing a submit success message to the user by rendering a component rather that an alert window or would that require make a class out of the form

**Comment by khaoptimist97** [comment]
As for using reset in onChange() of something inside the form? Anyone have an idea. Please suggest me

**Comment by Aeon-Avinash** [comment]
Works perfectly with async/await
```
onSubmit={async event => {
              await handleSubmit(event)
              form.reset()
            }}
```
I tried various suggestions to reset the form on successful submission but to no avail. I was just about to give up on Final Form and move back to Formik.

But then I tried my luck with async/await and it works like a charm! 
Thanks Final Form :1st_place_medal:

**Comment by NYCJacob** [comment]
@Aeon-Avinash this still doesn't work for me :(

**Comment by hdrdavies** [comment]
@NYCJacob Make sure your code looks something like this (following @Aeon-Avinash's example). It's working for me:

```
    <Form
      onSubmit={values => {
        console.log("values, ", values)
      }}
      render={({ handleSubmit, form }) => (
        <form
          onSubmit={async event => {
            await handleSubmit(event)
            form.reset()
          }}
        >
```

**Comment by NYCJacob** [comment]
@hdrdavies I get the form to reset, but that just clears the form.  I would like to display some kind of success/failure message.  I am afraid to try converting the form to a class and use state because final-form is doing so much internally.  I was looking at the response object on return but I still need state I think to conditionally render a message.

**Comment by golestanirad** [comment]
when i use

>  <Form
>       onSubmit={values => {
>         console.log("values, ", values)
>       }}
>       render={({ handleSubmit, form }) => (
>         <form
>           onSubmit={async event => {
>             await handleSubmit(event)
>             form.reset()
>           }}
>         >

because of that 

> form.reset()

my errors for validation are not shown.

**Comment by Soundvessel** [comment]
We really could use a handler to clear the contents of the form but does not affect form states like submitSucceeded which are often used to display a success message.

**Comment by bertho-zero** [comment]
For submission error:
```js
<form
  onSubmit={async event => {
    const res = await handleSubmit(event)
    form.reset()
    return res
  }}
>
```

**Comment by avbee** [comment]
Regarding @golestanirad post on validation errors not showing - I had the same problem and it took me a while to find the solution. I think it's not because of form.reset(). In my case, when I had validation errors, async handleSubmit was not executed at all and returned undefined, then form reset was executed. What worked for me was checking if handleSubmit is undefined or returns empty object before resetting the form.

**Comment by VincentCharpentier** [comment]
@golestanirad you don't have a `form` variable so you're calling `reset()` on undefined variable, that must be your issue.
If your destructure `form` in render property, then also extract `reset` function and call it directly:
https://github.com/final-form/react-final-form/issues/21#issuecomment-349024729

**Comment by leonardyrj** [comment]
Funcionou dessa forma
`const onSumbit = (value,form) => {
console.log(values)
setTimeout(form.reset)
}`

**Comment by tomkis** [comment]
Not sure if i am doing something wrong.

However - `form.reset` used as described above indeed resets its values but does not reset field state. Which results in validation errors after the submission.

So what I have to do is to reset each individual field state manually like:

```javascript
              handleSubmit(ev)?.then(() => {
                form.reset();
                form.resetFieldState("amount");
                form.resetFieldState("ingredient");
              });
```

So either I am missing some prop (which I don't seem to see in docs) which would reset not only values but also whole field state or `form.reset` does not work as one would expect.

**Comment by VincentCharpentier** [comment]
@tomkis 
1. you code will only reset if you handleSubmit is async or excplicitly return a promise (to execute the "?.then" callback)
2. What part of field state are you talking about ?
because once the reset is done your validation function get the initialValues, which can be valid or not depending on your validation function

**Comment by tomkis** [comment]
ad 1) yes I am well aware of that

ad 2) - i am talking about `touched` flag which remains true even after resetting the form - only `resetFieldsState` resets it back.

**Comment by VincentCharpentier** [comment]
I'm seeing the same issue when I tried (here https://codesandbox.io/s/epic-platform-wtm5s)

Maybe you could use "dirtySinceLastSubmit" instead ?

**Comment by soroushchehresa** [comment]
**This works for me**

```JSX
import React from 'react';
import { Form } from 'react-final-form';

const Component = () => {
  const handleResetForm = null;

  const handleSubmitForm = () => {
    // Do something...
    handleResetForm();
  };

  return (
    <Form
      onSubmit={handleSubmitForm}
      render={({ handleSubmit, pristine }) => {

        // Referenced the reset method to out of form
        if (!handleResetForm && form && form.reset) {
	  handleResetForm = form.reset;
        }

        return (
          <form onSubmit={handleSubmit}>
            ...
          </form>
        );
      }}
  );
}
```

` "final-form": "^4.18.5"`
` "react-final-form": "^6.3.0"`

**Comment by VincentCharpentier** [comment]
@soroushchehresa quick notes:
- you are reassigning a const variable. 
- you should add `form` in the render prop function

This should be enough:

```jsx
<form onSubmit={handleSubmit.then(form.reset)}>
```

**Comment by soroushchehresa** [comment]
@VincentCharpentier Thanks for the notes.
In my case, the `handleSubmit` method doesn't return a promise!

**Comment by VincentCharpentier** [comment]
Ah ok. Then I would suggest something like this:

```jsx
<form 
  onSubmit={
    async (...args) => {
      await handleSubmit(...args);
      form.reset();
    }
  }>
```

**Comment by soroushchehresa** [comment]
@VincentCharpentier My `handleSubmit` method doesn't return a promise,
So I can't use `await` or `then`. My suggested example is just for non-async flows, something like using forwarding refs!

[Async Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
[Forwarding Refs](https://reactjs.org/docs/forwarding-refs.html)

**Comment by douglasjunior** [comment]
I have the same problem of the @tomkis.

When call `setTimeout(form.reset)` the global form state is cleared, but the fields states stay with `touched` and others properties preserved.

A very ugly solution is to call `form.resetFieldState` to all fields.

```js
    const onSubmit = useCallback(async values => {
        try {
            await axios.post(...);

            setTimeout(() => {
                Object.keys(values).forEach(key => {
                    form.resetFieldState(key);
                });
                form.reset();
            });
        } catch (err) {
            ...
        }
    }, []);
```

**Comment by martinnov92** [comment]
I do it this way:

```js
const [formKey, setFormKey] = useState(Date.now());
...
<Form
  key={formKey}
  ...
  onSubmit={() => {
    // save to server
   setFormKey(Date.now());
  }}
/>
```

**Comment by apiwonska** [comment]
I wanted my form to reset fields after form is successfully submitted. This is the solution working in my case: 
```
<Form onSubmit={this.onSubmit}>
          {({handleSubmit, form, submitSucceeded}) => {
            if (submitSucceeded) {
              form.reset();
              form.resetFieldState('token');
              form.resetFieldState('password');
            }
            return (
            < form onSubmit = {handleSubmit} >
```
It's a pitty form.reset() does not automatically turn fields touched property to false, which for my form results showing validation errors (fields are required).

**Comment by michalmodrzejewski** [comment]
`Final-form` introduced new type in `4.20 version`
https://final-form.org/docs/final-form/types/FormApi

Quote from docs:
"`restart`
`() => void`
Resets all form and field state. Same as calling reset() on the form and resetFieldState() for each field. Form should be just as it was when it was first created."

Example code: 
`const onSumbit = form => setTimeout(() => form.restart)`
or with destructuring
`const onSumbit = { restart } => setTimeout(() => restart())`

**Comment by bertho-zero** [comment]
Remember that your `onSubmit` function not only receives `values`, but also the `form` object:

```js
function MyComponent() {
  const mySubmit = useCallback(
    (values, form) => {
      // Do what you want with your values...

      form.restart(); // or form.reset()
    },
    [/* ... */]
  );

  return (
    <Form
      onSubmit={mySubmit}
      component={MyForm}
    />
  );
}
```

**Comment by wontheone1** [comment]
> Here's a working sandbox with [my suggestion from above](https://github.com/final-form/react-final-form/issues/21#issuecomment-349024729).
> 
> [![Edit 🏁 React Final Form - Reset After Submit](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/m40yyj2nyx)

Doesn't seem to work with final-form 4.20.1 and react-final-form 6.5.1. @erikras 
Solved it using the second argument of `onSubmit` function which is the form.
```
const onSubmit = async (values, form) => {
    handleCalculate();
    console.log(form);
    setTimeout(() => form.initialize({}), 10);
    form.resetFieldState("amount_known");
    form.resetFieldState("used_electricity_amount");
  }

<Form
      onSubmit={onSubmit}
```

**Comment by srdjanblagojevic** [comment]
I think that this is the best practice.

final-form handleSubmit method has 3 parameters, values, form and callback. 
You need to point which method will be called on callback,, and you can add form.reset for that.
In this sample, I'm collecting only edited values, and sending them to my `handleFormSubmit` async method.

`<Form
	validate={validateFields}
	onSubmit={(values, form, callback) => {
		// eslint-disable-next-line no-param-reassign
		callback = form.reset;
		const changedValues = {};
		Object.keys(form.getState().dirtyFields).forEach(propName => {
			changedValues[propName] = values[propName]
		});
		return handleFormSubmit(changedValues);
	}}`

**Comment by bertho-zero** [comment]
There is no more need to do this kind of workaround, I made a PR that allows the reset during the submission: https://github.com/final-form/final-form/pull/363/files#diff-582693474d2a90e13161b9d64da11dd53a1e4a811df74d614d87463fffa1c8d7

You can now simply do:

```js
const onSubmit = (values, form) => {
  // what do you want
  form.reset();
}
```

**Comment by Soundvessel** [comment]
Wouldn't it make more sense to use `form.initialize` so you keep the `submitSuccess` state? You can pass an empty object or whatever you previous used for initial values. I think this also sets the form state of `pristine` to true again too so you can use that state with `submitSuccess` to determine the first submission vs second etc.

```js
  const onSubmit = useCallback(
    async function onChangePasswordFormSubmit(values, form) {
      try {
        await updatePassword(values)
        // clears focus if submit via enter press
        document.activeElement.blur()
        // re-initialize form AFTER submitSuccess to prevent re-focus on first field
        setTimeout(() => form.initialize({}), 20) // resets form without losing submitSucceeded state
        return undefined // triggers submitSuccess state
      } catch (error) {
        console.error(error)
        return mapErrors(error)
      }
    },
    [ updatePassword]
  )
```

**Comment by bertho-zero** [comment]
It depends on the need, everyone can do an `initialize`, a `reset` or a `restart`.

**Comment by fkunecke** [comment]
@bertho-zero has the right idea, but I found that calling `form.reset()` clears the form, then runs validation. I found it's better to call `form.restart()` because it doesn't run validation. An example use case is a user opens up a dialog with a form, clicks a field, then closes the dialog. Because the field has been `touched`, validation may render an error.

Here's my `handleSubmit`:

```
  const handleSubmit = async(data, form) => {
    setLoading(true);
    const result = await doWork(data);
    setLoading(false);
    handleClose(form);
  }

...

const handleClose = (form) => {
  onClose();
  // if we've been passed a form, restart it to clear without validation
  form && form.restart && form.restart();
};
```

**Comment by vijaychouhan-rails** [comment]
[Ref](https://formik.org/docs/migrating-v2#resetform)

```
const handleSubmitForm = (values, action) => {
    console.log("Form values", values)
    CALL_AN_API.then((res) => {
      action.resetForm(); // Reset the form to initialValues
    })
  };

```
```
<Formik
  initialValues={initialValues}
  onSubmit={handleSubmitForm}
  validationSchema={validationSchema}
  enableReinitialize
>
....
</Formik>
```
