### ISSUE TITLE
input.onBlur does not make field touched

### ISSUE THREAD

**Issue by davidhenley** [erikras/react-final-form#22]
input.onChange()  and input.onBlur() by themselves do not make a field touched. You MUST call input.onFocus() as well as onBlur to actually make the field touched.

```
export const CustomerSearch = (({ input, meta, label, ...rest }) => {
  return (
    <Form.Field>
      <label>{label}</label>
      <Search
        {...input}
        {...rest}
        list={[
          { title: 'thing 1', description: 'desc 1' },
          { title: 'thing 2', description: 'desc 2' },
        ]}
        onChange={result => input.onChange(result)} // this works
        onBlur={() => input.onBlur()} // this will not mark field as touched
      />
      <div className="field-error-text">{meta.touched && meta.error}</div>
    </Form.Field>
  );
})
```

You have to call onFocus if you are going to call onBlur. This will make it work. onBlur by itself should make the field touched in my opinion

**Comment by erikras** [comment]
Published fix in [`final-form v1.2.1`](https://github.com/final-form/final-form/releases/tag/v1.2.1).
