### ISSUE TITLE
How to do nested objects in Final forms?

### ISSUE THREAD

**Issue by kavink** [erikras/react-final-form#25]
If I want my final forms object on submit to look like this how would I do it ?
```
{
    name : 'kk'
    address: {
        street: '123 abc',
        city: 'sf'
    }
}
```
I know something like this is in works and will be there in future: https://redux-form.com/7.1.2/examples/fieldarrays/

but wondering if something like what I want is possible now ?

**Comment by erikras** [comment]
Yep. Fully supported, with dot syntax.
```jsx
<Field name="name" component="input"/>
<Field name="address.street" component="input"/>
<Field name="address.city" component="input"/>
```

**Comment by erikras** [comment]
Re: arrays... [YES!](https://github.com/erikras/react-final-form/issues/2#issuecomment-348929548)

**Comment by kavink** [comment]
@erikras  Do we have example code of doing exactly what u mentioned with dot syntax ? I was looking at Arrays example, wondering if we can have a similar code to add object in dot value, by using similar layout as Add/Remove ?

**Comment by erikras** [comment]
Related: the new [Prefixed Fields Example](https://github.com/final-form/react-final-form#prefixed-fields).
