### ISSUE TITLE
validateOnBlur not pass to final-form

### ISSUE THREAD

**Issue by elv1n** [erikras/react-final-form#27]
React react-final-form component collect config for final-form and there not exist property `validateOnBlur`
```
const config: Config = {
      debug,
      initialValues,
      onSubmit,
      validate
    }
```
Any reasons to skip `validateOnBlur` property?

**Comment by erikras** [comment]
Fix published in [`v1.1.1`](https://github.com/final-form/react-final-form/releases/tag/v1.1.1).
