### ISSUE TITLE
initialize is not a function

### ISSUE THREAD

**Issue by linashredinger** [erikras/react-final-form#31]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

Form does not filled using initialize method.

### What is the expected behavior?

Fill form after form is created.

### Sandbox Link

https://codesandbox.io/s/xo33o77j7q

### What's your environment?

pls, see sandbox

### Other information

i posted a question for you in tracker, but it was ignored so i tried myself and this is what i got

**Comment by erikras** [comment]
Upgrading the sandbox to `react-final-form v1.1.0` fixed it. 😄

**Comment by linashredinger** [comment]
Many thanks
