### ISSUE TITLE
Cleanup old/merged branches

### ISSUE THREAD

**Issue by MichaelDeBoey** [erikras/react-final-form#7]
The following branches are all merged into `master`, so I guess they can be deleted?

- [`missing-initialize-prop`](https://github.com/erikras/react-final-form/tree/missing-initialize-prop)
- [`multi-select-issue`](https://github.com/erikras/react-final-form/tree/multi-select-issue)

Just keeping the repo a bit cleaner 🙂

**Comment by erikras** [comment]
Man! A stickler for cleanliness! Cleaned.
